import pygame

BG_COLOR = (0, 0, 0)
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60


PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_SPEED = 3.5
PLAYER_IMAGE_PATH = "obrazk/R.png"
PLAYER_BULLET_IMP = "obrazky/bullet.png"
P_BULLET_SPEED = 5

ENEMY_IMAGE_PATH = "obrazky/alien{}.png"
ENEMY_SCALE = 1
ENEMY_SPEED = 2
ENEMY_DROP = 15
ENEMY_BULLET_IMP = "obrazky/alien_bullet.png"
E_BULLET_SPEED = 4

EXPLOSION_IMP = "obrazky/exp{}.png"

BOSS_SCALE = 3

EHP_BAR_WIDTH = 50
EHP_BAR_HEIGHT = 10
WHITE = (255,255,255)
BLACK = (0,0,0)
GREEN = (0,255,0)
YELLOW = (255,255,0)
RED = (255,0,0)